apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgresql
data:
  DB_HOST: postgresql-service
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_NAME: coworkingspace
---
apiVersion: v1
kind: Pod
metadata:
  name: db-secret
spec:
  containers:
  - name: envars-container
    image: nginx
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbp-secret
          key: db-password